a, b, c, d, e = map(int, input().split())
ans1 = (a * 6 + b * 3 + c * 2 + d + e * 2)
a, b, c, d, e = map(int, input().split())
ans2 = (a * 6 + b * 3 + c * 2 + d + e * 2)
print(str(ans1) + " " + str(ans2))